package com.mact.proxyproof.dataclass

data class Dates(
    var thirty : Any? = null,
    var twentyNine : Any? = null,
    var twentyEight : Any? = null,
    var twentySeven : Any? = null,
    var twentySix : Any? = null,
    var twentyFive : Any? = null,
    var twentyFour : Any? = null,
    var twentyThree : Any? = null,
    var twentyTwo : Any? = null,
    var twentyOne : Any? = null,
    var twenty : Any? = null,
    var ninteen : Any? = null,
    var eighteen : Any? = null,
    var seventeen : Any? = null,
    var sixteen : Any? = null,
    var fifteen : Any? = null,
    var fourteen : Any? = null,
    var thirteen: Any? = null,
    var twelve : Any? = null,
    var eleven : Any? = null,
    var ten : Any? = null,
    var nine : Any? = null,
    var eight : Any? = null,
    var seven : Any? = null,
    var six : Any? = null,
    var five : Any? = null,
    var four : Any? = null,
    var three : Any? = null,
    var two : Any? = null,
    var one : Any? = null
)
